services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///mydb.sqlite3
    volumes:
      - ./mydb.db:/app/mydb.db
      - ./migrations:/app/migrations
      - .:/app
    command: uvicorn --reload --host 0.0.0.0 --port 8000 --log-level debug app.main:app